### PR TITLE
add new options to /sandbox/public_token/create

### PR DESCRIPTION
**Pull request by michaelckelly**

### CODE REVIEW

**Comment by nathankot** [comment]
Tests should pass after this gets merged on top of #218

**Comment by PeasOfMind** [comment]
Any updates on this PR? I would love to see this functionality added to match with the docs: plaid.com/docs/#custom-sandbox

Also happy to help!

**Comment by cgfarmer4** [comment]
@PeasOfMind adding them in the middle of the function here would create a full version rev due to a breaking change. Do you have ideas on how to tag them in otherwise?

**Comment by PeasOfMind** [comment]
Hmm I'm not seeing how it could be a breaking change. If the user doesn't pass in `override_username` or `override_password`, the options payload wouldn't change right?

**Comment by otherchen** [comment]
@PeasOfMind Yep, it shouldn't be a breaking change because it's using keyword arguments. 
I'll try and see if we can get this reviewed by our next release (~2 weeksish)

**Pull request merged**
