### PR TITLE
Use Faraday for the HTTP client

### PR DESCRIPTION
**Pull request by chrisb**
Hey Plaid! We're interested in using the Plaid rubygem however we require low-level access to response data. Instead of monkey-patching the `Plaid` classes we decided to move the HTTP client to Faraday under the hood (instead of using `Net::HTTP` directly) whilst maintaining the existing interfaces. Faraday allows us to inject our own middleware or response handlers.

It looks like this gem may have been written with the intention of specifically avoiding external dependencies; if that is a hard requirement feel free to decline this PR. I've tested this against credentials from my own personal (development) Plaid account and hope that is sufficient. I'm happy to make changes as required.

### CODE REVIEW

**Comment by chrisb** [comment]
Looks like there's a failing test which I cannot reproduce; are you guys able to point me in the right direction?

**Comment by be9** [comment]
@chrisb thanks for your PR! I'll see if we are OK with adding faraday and will get back to you.

**Comment by be9** [comment]
@chrisb good news! We will be using faraday! 😄 

I'll work on integrating your PR to our codebase.

**Comment by be9** [comment]
@chrisb this has become a part of #175, so I close this PR. Of course, you'll get the credits in the CHANGELOG :)

**Pull request closed without merging**
