### PR TITLE
Add optional webhook_url param to user.upgrade to create a webhook wh…

### PR DESCRIPTION
**Pull request by ldrbrandon**
…en upgrading to connect

### CODE REVIEW

**Comment by rubendinho** [comment]
Could this also be used to update the webhook if a user is already authorized for Connect?

**Comment by ldrbrandon** [comment]
Yea definitely, from my understanding/testing with it, it looks like if you resubmit a web hook it replaces whatever existing one was there. That was my experience at least, you'd have to double check with support@plaid.com to be sure.

**Comment by ldrbrandon** [comment]
@rubendinho I am actually wrong on the updating part. You will get a Plaid Product already enabled error if you try and upgrade a user to connect who already has connect. I'm working on another user method that will simply do a PATCH to /connect to update/create a webhook. I'll post soon

**Comment by be9** [comment]
Implemented this feature for 2.0.0 in #109. Closing this PR, thanks!

**Pull request closed without merging**
