### PR TITLE
replace global singleton client with instances, so we can have test/prod clients at the same time

### PR DESCRIPTION
**Pull request by benissimo**
This is the same as @herval's pull request.
I just marked the failing specs with skip.
Those were already specs that, even in the official plaid-ruby branch, were marked as pending anyway.

### CODE REVIEW

**Comment by michaelckelly** [comment]
@benissimo - Thank you for taking the time to fix up the pull request and get the tests passing. This is poor timing (and apologies for not clarifying this earlier), but Plaid is actually in the process of overhauling the library (https://github.com/plaid/plaid-ruby/issues/106) to bring it more in line with the standards of our other officially supported client libraries!

**Comment by benissimo** [comment]
@michaelckelly I hope that #106 can include this type of improvement. Note for example how Plaid-java doesn't rely on singleton client.  It'd be great if #106 made this pull request (#105) obsolete.

Note that it doesn't have to avoid the singleton approach to solve this. The stripe-ruby library, for example, uses a singleton client but allows the caller to pass in the api_key on a per request basis. A similar approach could work here too, allowing the user to pass in customer_id, secret, and environment location overrides with their request. Either way could work; the key is just having some thread-safe way to support using more than one Plaid environment at a time.

**Comment by michaelckelly** [comment]
@benissimo - Thanks for expounding on those thoughts - I've passed it along to the team. I'll direct them here if they have any questions, too!

**Comment by be9** [comment]
@benissimo Thank you for your suggestions, I've incorporated them into the major rewrite of the plaid-ruby which has just been released as 2.0.0.alpha! More about custom clients [here](https://github.com/plaid/plaid-ruby/#custom-clients).

I encourage you to test the alpha version, and your feedback would be greatly appreciated!

Closing this PR now.

**Pull request closed without merging**
