### PR TITLE
Test Cleanup

### PR DESCRIPTION
**Pull request by volodymyr-mykhailyk**
Fix raise_error warnings
Use correct folder structure under spec

### CODE REVIEW

**Comment by rilian** [comment]
ncie

**Comment by dmerrick** [comment]
Thanks for the PR, this is awesome.

**Comment by dmerrick** [comment]
Thanks!

**Comment by volodymyr-mykhailyk** [comment]
Sorry, didn't seen email about rebasing. Thanks for merging

**Pull request merged**
