### PR TITLE
Add generic processor token method

### PR DESCRIPTION
**Pull request by lukeguild**
Add a new method to generate processor tokens through the generic token create route.
Does not alter or affect any existing exported functions or types.

### CODE REVIEW

**Comment by javierjulio** [comment]
Dwolla/Plaid user here. 👋🏻 Any reason this doesn't include Dwolla or other processors?

**Comment by skylarmb** [comment]
@javierjulio any processor other than `stripe` or `apex` will just hit the generic endpoint `'processor/token/create'`, which includes dwolla! 

https://github.com/plaid/plaid-ruby/pull/256/files#diff-ba606312e0ff248bacd1dae0ec31a4cbR144

**Comment by javierjulio** [comment]
Interesting, thanks! I had asked because the Dwolla implementation still uses the `processor/dwolla/processor_token/create` endpoint so wasn't sure if it was applicable here.

**Comment by skylarmb** [comment]
@javierjulio as I understand it we are migrating processors to this generic endpoint rather than processor-specific endpoints (in order to be able to add new processors more easily). Correct me if I'm wrong @lukeguild as this is not my PR

**Comment by lukeguild** [comment]
Yep! That's the goal. We're planning on adding more processors and this change (and the endpoint behind it) allows us to do so without pushing new versions of the API and client libraries. Dwolla is compatible with the new endpoint if you want to switch! We'll be leaving the existing one for compatibility though.

**Comment by javierjulio** [comment]
@skylarmb @lukeguild awesome thanks for clarifying! ❤️ Once the update is out, we'll switch to using the generic one then for Dwolla.

**Pull request merged**
